name: Lint commit message

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
  workflow_dispatch:

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: ls
      - run: git tag
      - name: Set up convco
        run: |
          curl -OL https://github.com/convco/convco/releases/latest/download/convco-deb.zip
          unzip convco-deb.zip
          sudo dpkg -i convco*.deb
      - run: convco version
      # - uses: actions/setup-node@v3
      #   with:
      #     node-version: 18
      # - name: Install commitlint
      #   run: |
      #     npm install -g @commitlint/cli @commitlint/config-conventional
      #     echo "module.exports = {extends: ['@commitlint/config-conventional']}" > commitlint.config.js
      # - name: Validate pull request title with commitlint
      #   if: github.event_name == 'pull_request'
      #   run: echo "${{ github.event.pull_request.title }}" | commitlint --verbose
      # - name: Validate pull request title with commitlint
      #   if: github.event_name == 'workflow_dispatch'
      #   run: gh pr view --json title -t "{{.title}}" | commitlint --verbose
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}