name: Publish package to GitHub Packages
on:
  release:
    types: [created]
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - "VRCL/*"
      - ".github/workflows/*"
jobs:
  publish-:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
      - name: Install to local repository
        run: mvn clean install
      - name: Publish package
        run: mvn deploy --batch-mode -f VRCL/pom.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

